#! /bin/bash
#./runCDN -i ~/.ssh/id_rsa -u drunkbug -o "ec2-54-166-234-74.compute-1.amazonaws.com" -p "40123" -n "example.com"
HOSTS=(ec2-52-90-80-45.compute-1.amazonaws.com
    ec2-54-183-23-203.us-west-1.compute.amazonaws.com
    ec2-54-70-111-57.us-west-2.compute.amazonaws.com
    ec2-52-215-87-82.eu-west-1.compute.amazonaws.com
    ec2-52-28-249-79.eu-central-1.compute.amazonaws.com
    ec2-54-169-10-54.ap-southeast-1.compute.amazonaws.com
    ec2-52-62-198-57.ap-southeast-2.compute.amazonaws.com
    ec2-52-192-64-163.ap-northeast-1.compute.amazonaws.com
    ec2-54-233-152-60.sa-east-1.compute.amazonaws.com)
DNSSERVER="cs5700cdnproject.ccs.neu.edu"

while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -p|--port)
    PORT="$2"
    shift
    ;;
    -o|--origin)
    ORIGIN="$2"
    shift
    ;;
    -n|--name)
    NAME="$2"
    shift
    ;;
    -u|--username)
    USERNAME="$2"
    shift
    ;;
    -i|--keyfile)
    KEYFILE="$2"
    shift
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done

echo "run http"
for HOST in "${HOSTS[@]}"
do
    echo "$HOST"
    ssh -i $KEYFILE -n -f $USERNAME@$HOST "sh -c 'cd ~/cdn/; nohup ./httpserver -p $PORT -o $ORIGIN &'"
    #> /dev/null 2>&1
done

echo "run dns"
    ssh -i $KEYFILE -n -f $USERNAME@$DNSSERVER "sh -c 'cd ~/cdn/; nohup ./dnsserver -p $PORT -n $NAME > /dev/null 2>&1 &'"
